appzen-oss/mastermind-kibana

- .ci/build_docker.sh
- package.json
- src/dev/build/tasks/os_packages/docker_generator/templates/build_docker_sh.template.ts
- yarn.lock
prevents building docker image with yarn build command
> Jenkins test

- package.json
- yarn.lock
* Update package.json with EUI Package to 30.2.0-10
* Update yarn lock file
> update eui package to 30.2.0-10

- package.json
- yarn.lock
> testing registry with  eui version

- src/core/public/chrome/ui/header/collapsible_nav.tsx
- src/core/utils/default_app_categories.ts
**Changes**
* adds aaa App Category
* renders aaa App Category in left nav
> Mad 1109 aaa   invoice app left nav   add aaa category

- package.json
- src/core/public/chrome/ui/top_navigation.tsx
- src/core/server/rendering/views/template.tsx
- yarn.lock
Updated the loading message to be more generic
> Added app switcher changes to mastermind kibana

- package.json
- yarn.lock
Fixes breadcrumb redirection
Fixes common-config left navigation
> Update the latest version of app switcher

- package.json
- yarn.lock
> Update App switcher and common config version

- package.json
- yarn.lock
Fix switch user redirection issue
and landing page support for SystemAdmin in AAA
> Updated the latest app switcher and common config versions

- package.json
- src/core/public/chrome/ui/top_navigation.tsx
- yarn.lock
Added support for notifications in top nav
> Update latest app-switcher and common-configs version

- package.json
- yarn.lock
- Added new left nav for Chart of Accounts
> AAP-253 COA Mapping UI

- package.json
- yarn.lock
> Update the latest app-switcher and common-configs version

- package.json
- yarn.lock
> Update app-switcher version - styling fixes

- package.json
- src/core/public/chrome/ui/top_navigation.tsx
- yarn.lock
> Update app-switcher version

- package.json
- src/core/public/chrome/ui/top_navigation.tsx
- yarn.lock
fix appzen logo issue
fix change password api
> Updated latest app-switcher version

- package.json
- yarn.lock
Update latest app-switcher & common-configs version
> AAP-271 COA Master Data UI Left Nav Changes

- package.json
- src/core/public/chrome/ui/top_navigation.tsx
- yarn.lock
> Import latest app-switcher changes in mastermind-kibana

- package.json
- yarn.lock
- Fix for SARO users and left nav changes
> Import latest app-switcher and common-configs version in kibana

- package.json
- src/core/public/chrome/ui/top_navigation.tsx
- yarn.lock
- Fixes organization dropdown issue
> Import latest app-switcher version

- package.json
- yarn.lock
Add contact support and support portal left nav options
> Import latest app-switcher and common-configs version

- package.json
- src/core/public/styles/_base.scss
- yarn.lock
Import latest app-switcher version
Maintaining side nav state between apps
> Add a class to support hiding the animation added by default

- package.json
- src/core/public/chrome/ui/top_navigation.tsx
- yarn.lock
Added zendesk api for support portal
> Import latest app-switcher version in mastermind

- package.json
- yarn.lock
Update app-switcher and common-configs version to latest
> AAP-334 Payment Term Mapping & Master Data UI Left Nav Changes

- package.json
- src/core/public/chrome/ui/top_navigation.tsx
- yarn.lock
Add mobile view changes for
Notification Worklist and Invoice Details page
> Update latest app-switcher version

- package.json
- yarn.lock
> Imported latest app-switcher and common-config versions

- package.json
- yarn.lock
Added echarts dependency for landing page
> Fix dependency for common-configs

- package.json
- yarn.lock
> added latest versions

- package.json
- yarn.lock
> Update app-switcher and common-configs package

- package.json
- yarn.lock
> EXP-5566 imported latest versions master

- package.json
- yarn.lock
> EXP-5566 version update

- package.json
- yarn.lock
> Imported latest app-switcher and common-config version

- package.json
- yarn.lock
> Update elastic eui version

- src/core/public/chrome/doc_title/doc_title_service.ts
- src/core/server/rendering/views/template.tsx
> Add support to set base title via plugins

- src/core/public/chrome/chrome_service.mock.ts
> Fix build issue

- package.json
- yarn.lock
> Import latest app-switcher common-configs eui version

- package.json
- yarn.lock
> Updated internal_protos package

- package.json
- yarn.lock
> Update app switcher version - notifications API

- package.json
- yarn.lock
> AAP-900: GR Master data left nav

- package.json
- yarn.lock
> update app-switcher and utility version

- package.json
- yarn.lock
> Imported latest app-switcher and common-configs version

- package.json
- src/core/public/rendering/_base.scss
- yarn.lock
update font in mastermind kibana root
import latest app-switcher version
> AAP-1005-update-font

- package.json
- yarn.lock
> Mad 3297 import app switcher version

- package.json
- yarn.lock
> AENG-191 version change

- package.json
- yarn.lock
> SEC-649: Upgarding app-switcher version for new heap Ids

- package.json
- yarn.lock
> AENG- 191 imported latest app switcher version

- package.json
- yarn.lock
> Imported latest versions

- package.json
- yarn.lock
> AENG-216 fix build issue

- package.json
- yarn.lock
> AAP-1109:Scope & Scope Group Management - Proto update

- package.json
- yarn.lock
> AENG-254 imported latest versions

- package.json
- yarn.lock
> Import latest app-switcher and common-config changes

- package.json
- yarn.lock
> AENG-267 imported latest versions

- src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile
> tests dockerfile workaround, comment out check sum

- package.json
- yarn.lock
> AENG-92 Imported latest version of elastic eui 30.2.0-64

- package.json
- yarn.lock
> AENG-299 Imported latest versions

- package.json
- yarn.lock
> AENG-296 Imported latest versions

- package.json
- yarn.lock
> AAP-1329 Automations Left Nav Changes

- package.json
- yarn.lock
Automations Left Nav Changes - Minor Bugfix
> AAP-1329 Automations Left Nav Changes - Minor Bugfix

- package.json
- yarn.lock
> AENG-377 imported latest versions

- package.json
- yarn.lock
> AENG-442 Import latest version

- package.json
- yarn.lock
> AENG-446 imported latest versions

- package.json
- yarn.lock
> AENG-492 imported latest versions

- package.json
- yarn.lock
> AENG-509 import latest version

- package.json
- yarn.lock
> AAP-1287: Updating internal protos to 1.7.9 - report cron metadata

- package.json
- yarn.lock
> AENG-534 imported latest versions

- package.json
- yarn.lock
> AAP-1287: renaming autonomous ap reports minor

- package.json
- yarn.lock
> AENG-539 import latest versions

- package.json
- yarn.lock
> EXP-6471 Import latest versions

- package.json
> AAP-1521: adding jszip dependency

- package.json
- yarn.lock
This fixes the component unmounting issue on resize
> Upgrade react-grid-layout version

- package.json
- yarn.lock
> Import latest common-configs and app-switcher

- package.json
- yarn.lock
> AENG-336: Update eui version

- package.json
- yarn.lock
AAP-1567 | Update Latest App-Switcher Version
> AAP-1567 | Update Latest App-Switcher Version

- package.json
- yarn.lock
> Import latest app-switcher and common-config versions

- package.json
- yarn.lock
> AENG-120 enhance: updated elastic/eui version.

- package.json
- yarn.lock
> AENG-555: Update eui version

- package.json
- yarn.lock
> AENG-601: Update internal protos version

- package.json
- yarn.lock
> Import latest app-switcher, common-configs & eui versions

- package.json
- yarn.lock
AAP-1724 | Update app-switcher, common config & eui
> AAP-1724 | Update app-switcher, common config & eui - master PR

- package.json
- yarn.lock
AAP-1724 | Update app-switcher, common config & eui
> AAP-1724 | Update app-switcher, common config & eui - m3 branch PR

- src/core/public/chrome/ui/top_navigation.tsx
> Fix: Pass passwords as part of request body

- package.json
- yarn.lock
> AENG 637: update app-switcher and common-config versions

- package.json
- yarn.lock
> Added aws quicksight sdk dashboard package

- package.json
- yarn.lock
Fix automations left nav not visible to Approval:WorkflowAdmin role
> AAP-1859 Fix automations not visible to Approval WorkflowAdmin - app-switcher PR: M3 branch

- package.json
- yarn.lock
Fix automations left nav not visible to Approval:FunctionalAdmin & AAA:FunctionalAdmin role
> AAP-1859 Fix automations not visible to Approval WorkflowAdmin - app-switcher PR: Master branch

- package.json
- yarn.lock
AAP-1865 | Upgrade app-switcher
> AAP-1865 Fix recurring notifications API call

- package.json
- yarn.lock
> AENG-610_mastermind_kibana_version_bump

- package.json
- yarn.lock
> EXP-6690 updating app-switcher version

- package.json
- yarn.lock
> AENG-610 update common-config and appswitcher version

- package.json
- yarn.lock
> AENG-813 version bump

- package.json
- yarn.lock
> Import latest az packages

- package.json
- yarn.lock
> Import latest eui version

- package.json
- yarn.lock
> Update eui to 106

- package.json
- yarn.lock
> AENG-885 version bump kibana

- package.json
- yarn.lock
> AENG-749: Logrocket changes

- package.json
- yarn.lock
> AENG-914: import app-switcher and common-config version

- package.json
> import latest versions of app-switcher, common-configs and internal-protos

- package.json
- yarn.lock
> AENG-905 mm-apps app-switcher,common-config  version-bump

- package.json
- yarn.lock
> AENG-869: EUI version bump

- package.json
- yarn.lock
> AENG-870: Bump app switcher version

- package.json
- yarn.lock
> Import latest app-switcher and common-configs versions

- package.json
- yarn.lock
> Updated app-switcher version for MMA Deprecation Badge changes

- package.json
- yarn.lock
> AENG-966 update: bumped version 'common-configs' 'app-switcher'.

- package.json
- yarn.lock
> Update eui version in DEC3 hotfix

- package.json
- yarn.lock
> AENG-897 update proto version

- package.json
- yarn.lock
> update common-config and app-switcher version

- package.json
- yarn.lock
Bump up latest common-config and app-switcher as per this PR: 
https://bitbucket.org/appzeneng/az-ui/pull-requests/2133/diff
> EXP-6903 Updated console sandbox URL

- package.json
- yarn.lock
> AENG-966 update: bump version for common-config/appswitcher

- package.json
- yarn.lock
> Revert eui version (manager approval ux changes)

- package.json
- yarn.lock
Import latest app-switcher and common-configs versions
> AENG-1008-update-dependencies

- package.json
- yarn.lock
> AENG-1012: import app-switcher

- package.json
- yarn.lock
> Import latest eui version in kibana

- package.json
- yarn.lock
> [dec hotfix] AENG-905 mm-apps app-switcher, common-config version-bump for 

- package.json
- yarn.lock
> Import app-switcher and common-config versions

- package.json
- yarn.lock
> update az-ui packages

- package.json
- yarn.lock
> EXP-6916 version bump az-ui

- yarn.lock
> AENG-1054 update eui version

- package.json
- yarn.lock
> Updated app-switcher version for prod hotfix (deprecation message)

- package.json
- yarn.lock
> AENG-1074 appswitcher version bump

- package.json
- src/core/public/chrome/ui/top_navigation.tsx
- yarn.lock
(cherry picked from commit a3eb475f107bf9fa165dd36819b012ce3e36360d)
> AENG-981 hiding appswitcher on mobile-devices and updated appswitcher

- package.json
- yarn.lock
> update eui version

- package.json
- yarn.lock
> Updated Eui version

- package.json
- yarn.lock
> AENG-1039: import packages

- package.json
- yarn.lock
> AENG-1039: hotfix import packages

- package.json
- yarn.lock
> Import hotfix app-switcher and common-configs package

- package.json
- yarn.lock
> Updated internal proto version

- package.json
- yarn.lock
> AENG-968: import latest packages

- package.json
- yarn.lock
> AENG-967: Update Eui

- package.json
- yarn.lock
> ANA-948 updated version for app-switcher, common-config

- package.json
- yarn.lock
> AENG-1117: Bump Eui version

- package.json
- yarn.lock
> AENG-1099 Added yarn changes

- package.json
- yarn.lock
> AENG-1154: Update eui

- package.json
- yarn.lock
> AENG-1154: Bump Eui version

- package.json
- yarn.lock
> eui update - Master

- package.json
- yarn.lock
> updated eui to 30.2.0-133

- package.json
- yarn.lock
> AENG-1199 sync eui version 134

- src/core/public/chrome/ui/top_navigation.tsx
pass the new user details api in app-switcher
> AENG-1213-master-pr

- src/core/public/chrome/ui/top_navigation.tsx
Pass the new user details api in app-switcher
> AENG-1213-april-hotfix-pr

- package.json
- yarn.lock
> AENG-1046: Update app switcher and eui

- package.json
- yarn.lock
Import latest app-switcher version
> AENG-1599-import-app-switcher

- src/dev/build/build_distributables.ts
- src/dev/build/lib/config.ts
- src/dev/build/tasks/build_kibana_platform_plugins.ts
> AENG-1174: Fix build issue

- package.json
- yarn.lock
Import latest app-switcher version
> AENG-1599-switch-user-button

- package.json
- yarn.lock
> Update @az/app-switcher to version 2.22.3

- package.json
- yarn.lock
> AAP-4078 | Bump Internal Protos
